version: '3'
services:
  web:
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules #node_modulesはホストのディレクトリにマウントさせない https://github.com/sass/node-sass/issues/2165#issuecomment-347043659
    command: ash -c "npm install && npm run dev"
    stdin_open: true
    tty: true